webadmin/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UPM.Entities;
using webadmin.Models;

namespace webadmin.Controllers
{
    public class NoticiasController : Controller
    {
        private UnidosconmarinaEntities db = new UnidosconmarinaEntities();

        // GET: Noticias
        public ActionResult Index()
        {
            return View(db.Noticias.Include(a => a.AspNetUser).Include(a => a.AspNetUser1).ToList());
        }

        // GET: Noticias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Noticias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titulo,descripcion,lugar,fecha,fotoDefault,estatus,usuarioRegistro,usuarioUpdate,fechaRegistro,fechaUpdate")] Noticia noticia, HttpPostedFileBase file)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {

                    if (file != null)
                    {
                        string NombreArchivo = System.IO.Path.GetFileName(file.FileName);
                        string physicalPath = Server.MapPath("~/Content/images/noticias/" + NombreArchivo);
                        file.SaveAs(physicalPath);
                        noticia.fotoDefault = NombreArchivo;

                    }
                    db.Noticias.Add(noticia);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(noticia);
            }
            else
            {
                return View("~/Views/Account/Login.cshtml");
            }
        }


        // GET: Noticias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noticia noticia = db.Noticias.Include(a => a.AspNetUser).FirstOrDefault(x => x.id == id);
            if (noticia == null)
            {
                return HttpNotFound();
            }
            return View(noticia);
        }

        // POST: Noticias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titulo,descripcion,lugar,fecha,fotoDefault,estatus,usuarioRegistro,usuarioUpdate,fechaRegistro,fechaUpdate")] Noticia noticia, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    string NombreArchivo = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/images/banners/" + NombreArchivo);
                    file.SaveAs(physicalPath);
                    noticia.fotoDefault = NombreArchivo;
                }
                db.Entry(noticia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(noticia);
        }

        // GET: Noticias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noticia noticia = db.Noticias.Find(id);
            if (noticia == null)
            {
                return HttpNotFound();
            }
            return View(noticia);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> EliminarAsync(Noticia data)
        {
            try
            {
                Noticia noticia = db.Noticias.Find(data.id);
                db.Noticias.Remove(noticia);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha eliminado correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webadmin/Views/Noticias/Create.cshtml
@using Microsoft.AspNet.Identity;
@model UPM.Entities.Noticia

@{
    ViewBag.Title = "Create";
    var UserId = User.Identity.GetUserId();
    var userName = User.Identity.GetUserName();
}

<!-- @{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            Catálogos
        </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "Noticias")" class="kt-subheader__breadcrumbs-link">
                Banners
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Agregar Banner
            </a>

            <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
        </div>
    </div>

</div>
<!-- end:: Subheader -->
@using (Ajax.BeginForm("Create", "Noticias", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "successAction"

},
                new { @id = "modalForm", enctype = "multipart/form-data" }
                ))
{

    @Html.AntiForgeryToken()
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

        <div class="kt-portlet kt-portlet--mobile">

            <div class="kt-portlet__body">
                <h4>Agregar Banner</h4>
                <hr />
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <br />
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="fileinput-new img-thumbnail" style="width: 780px; height: 266px;">
                                <img src="~/assets/media/icons/camera2.png" alt="...">
                            </div>
                            <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 1280px; max-height: 366px;"></div>
                            <div>
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">Elegir Foto</span>
                                    <span class="fileinput-exists">Cambiar</span>
                                    <input type="file" name="file" id="file">
                                </span>
                                <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                            </div>
                        </div>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">
                        <div class="form-group">
                            <div class="">
                                <div class="checkbox">
                                    @Html.LabelFor(model => model.estatus, "Se publica?", htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.estatus)
                                    @Html.ValidationMessageFor(model => model.estatus, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>
                                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Titulo de la Noticia
                            </span>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>
                                @Html.EditorFor(model => model.lugar, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.lugar, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Lugar de la Noticia
                            </span>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>
                                @Html.TextBoxFor(model => model.fecha, "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control", type = "date" })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Fecha de la Noticia
                            </span>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>
                                <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @userName</span>
                                @Html.HiddenFor(model => model.usuarioRegistro, new { Value = UserId, htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.usuarioRegistro, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Usuario de Registro
                            </span>
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>
                                @Html.EditorFor(model => model.fechaRegistro, new { htmlAttributes = new { Value = System.DateTime.Now.ToString("MM/dd/yyyy"), @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5" } })
                                @Html.ValidationMessageFor(model => model.fechaRegistro, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Fecha Registro
                            </span>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div>
                                @Html.TextAreaFor(model => model.descripcion, new { @class = "required", @cols = 120, @rows = 20 })
                                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Descripción de la noticia
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Registrar" />
                    </div>
                </div>

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/assets/js/programacion/list.js"></script>
}

webadmin/Views/Noticias/Delete.cshtml
@model UPM.Entities.Noticia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Noticia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fotoDefault)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fotoDefault)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioUpdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaUpdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

webadmin/Views/Noticias/Details.cshtml
@model UPM.Entities.Noticia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Noticia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fotoDefault)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fotoDefault)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioUpdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaUpdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

webadmin/Views/Noticias/Edit.cshtml
@using Microsoft.AspNet.Identity;
@model UPM.Entities.Noticia


@{
    ViewBag.Title = "Edit";
    var UserId = User.Identity.GetUserId();
    var userName = User.Identity.GetUserName();
}

@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            CATALOGOS
        </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "Noticias")" class="kt-subheader__breadcrumbs-link">
                Noticias
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Editar Noticia
            </a>

        </div>
    </div>

</div>
<!-- end:: Subheader -->
@using (Ajax.BeginForm("Edit", "Empresa", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "successAction"

},
                            new { @id = "modalForm", enctype = "multipart/form-data" }
                            ))
{

    @Html.AntiForgeryToken()
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

        <div class="kt-portlet kt-portlet--mobile">

            <div class="kt-portlet__body">

                <div class="form-horizontal">
                    <h4>Editar Noticias</h4>
                    <hr />
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new img-thumbnail" style="width: 580px; height: 266px;">
                                    @if (!string.IsNullOrEmpty(Model.fotoDefault))
                                    {
                                        <img src="~/Content/images/banners/@Model.fotoDefault " alt="..." style="max-width: 580px; max-height: 266px;">
                                        @Html.HiddenFor(model => model.fotoDefault, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    }
                                    else
                                    {
                                        <img src="~/assets/media/icons/camera2.png" alt="...">
                                    }
                                </div>
                                <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 580px; max-height: 266px;"></div>
                                <div>
                                    <span class="btn btn-default btn-file">
                                        <span class="fileinput-new">Elegir Foto</span>
                                        <span class="fileinput-exists">Cambiar</span>
                                        <input type="file" name="file" id="file">
                                    </span>
                                    <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            @if (ViewBag.imageBytes != null)
                            {

                                <img width="150" height="150" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(ViewBag.imageBytes))" />
                            }
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-1">
                            <div class="form-group">
                                <div class="">
                                    <div class="checkbox">
                                        @Html.LabelFor(model => model.estatus, "Se publica?", htmlAttributes: new { @class = "control-label" })
                                        @Html.EditorFor(model => model.estatus)
                                        @Html.ValidationMessageFor(model => model.estatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>
                                    @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Titulo de la Noticia
                                </span>
                            </div>

                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div>
                                    @Html.EditorFor(model => model.lugar, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.lugar, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Lugar de la Noticia
                                </span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>
                                    @Html.TextBoxFor(model => model.fecha, "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control", type = "date" })
                                    @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Fecha de la Noticia
                                </span>
                            </div>
                        </div>
                    </div>
                    <br />

                    <div class="row">
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>

                                    <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @Model.AspNetUser.Email</span>
                                    @Html.HiddenFor(model => model.usuarioRegistro, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.usuarioRegistro, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Usuario de Registro
                                </span>
                            </div>

                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div>
                                    @Html.TextBoxFor(model => model.fechaRegistro, "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5" })
                                    @Html.ValidationMessageFor(model => model.fechaRegistro, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Fecha Registro
                                </span>
                            </div>
                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>

                                    <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @userName</span>
                                    @Html.HiddenFor(model => model.usuarioUpdate, new {Value = UserId, htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.usuarioUpdate, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Usuario de actualización
                                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div>
                                    @Html.EditorFor(model => model.fechaUpdate, new { htmlAttributes = new { Value = System.DateTime.Now.ToString("yyyy/MM/dd"), @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5" } })
                                    @Html.ValidationMessageFor(model => model.fechaUpdate, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Fecha de Actualización
                                </span>
                            </div>
                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-md-1">
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <div>
                                    @Html.TextAreaFor(model => model.descripcion, new { @class = "required", @cols = 120, @rows = 20 })
                                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Descripción de la noticia
                                </span>
                            </div>

                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Editar" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}