website/Controllers/AcercaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace website.Controllers
{
    public class AcercaController : Controller
    {
        // GET: Acerca
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult marina_del_pilar()
        {
            return View();
        }

    }
}

website/Controllers/CapacitacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace website.Controllers
{
    public class CapacitacionesController : Controller
    {
        // GET: Capacitaciones
        public ActionResult Index()
        {
            return View();
        }
    }
}

website/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UPM.Entities;

namespace website.Controllers
{
    public class RegistroController : Controller
    {
        private UnidosconmarinaEntities db = new UnidosconmarinaEntities();

        // GET: Padrons
        public ActionResult Index()
        {
            return View();
        }

        // GET: Padrons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Padron padron = db.Padrons.Find(id);
            if (padron == null)
            {
                return HttpNotFound();
            }
            return View(padron);
        }

        // GET: Padrons/Create
        public ActionResult Create()
        {
            ViewBag.votante = new SelectList(db.TipoVotantes, "id", "tipo_votante");
            return View();
        }

        // POST: Padrons/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nombre,paterno,materno,telefono,celular,direccion,comentario,rfc,curp,claveElectoral,votante,usuarioRegistro,usuarioUpdate,fechaRegistro,fechaUpdate,email,registroCompleto")] Padron padron)
        {
            if (ModelState.IsValid)
            {
                if (padron.nombre != null && padron.paterno != null && padron.telefono != null && padron.celular != null && padron.direccion != null && padron.rfc != null && padron.curp != null && padron.claveElectoral != null && padron.email != null)
                {
                    padron.registroCompleto = true;
                }
                else
                {
                    padron.registroCompleto = false;
                }
                padron.fechaRegistro = DateTime.Now.Date;
                db.Padrons.Add(padron);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(padron);
        }

        public async System.Threading.Tasks.Task<JsonResult> CreateAsync(HistorialContacto data, HttpPostedFileBase file)
        {
            try
            {
                HistorialContacto historial = new HistorialContacto();

                historial.FkPadron = data.FkPadron;
                historial.comentario = data.comentario;
                historial.fechaupdate = DateTime.Now;
                historial.usuarioRegistro = data.usuarioRegistro;

                db.HistorialContactoes.Add(historial);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha agregado el seguimiento correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }



        // GET: Padrons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Padron padron = db.Padrons.Find(id);
            if (padron == null)
            {
                return HttpNotFound();
            }
            return View(padron);
        }

        public async System.Threading.Tasks.Task<JsonResult> EliminarAsync(Padron data)
        {
            try
            {
                Padron padron = db.Padrons.Find(data.Id);
                db.Padrons.Remove(padron);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha eliminado correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> EliminarHistorialAsync(HistorialContacto data)
        {
            try
            {
                HistorialContacto historial = db.HistorialContactoes.Find(data.Id);
                db.HistorialContactoes.Remove(historial);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha eliminado correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> RegistroJson(Padron data, HttpPostedFileBase file)
        {
            try
            {
                if (data.nombre != null && data.paterno != null && data.telefono != null && data.celular != null && data.direccion != null && data.rfc != null && data.curp != null && data.claveElectoral != null && data.email != null)
                {
                    data.registroCompleto = true;
                }
                else
                {
                    data.registroCompleto = false;
                }

                data.fechaRegistro = DateTime.Now.Date;

                if(data.esImss == false)
                {
                    data.redJuventud = false;
                }

                db.Padrons.Add(data);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha registrado correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }
    }
}

website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Unidos con Marina</title>
    <meta charset="utf-8">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <![endif]-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/main.css" id="color-switcher-link">
    <link rel="stylesheet" href="~/Content/css/animations.css">
    <link rel="stylesheet" href="~/Content/css/fonts.css">
    <script src="~/Content/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
    <script src="~/Content/custom/js/vendors/sweetalert2.init.js" type="text/javascript"></script>
    <link href="~/Content/sweetalert2/dist/sweetalert2.css" rel="stylesheet" type="text/css" />

    <!--[if lt IE 9]>
        <script src="js/vendor/html5shiv.min.js"></script>
        <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="preloader">
        <div class="preloader_image"></div>
    </div>
    <!--[if lt IE 9]>
        <div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
    <![endif]-->
    <!-- search modal -->
    <div class="modal" tabindex="-1" role="dialog" aria-labelledby="search_modal" id="search_modal">
        <div class="widget widget_search">
            <form method="get" class="searchform form-inline" action="/">
                <div class="form-group">
                    <input type="text" value="" name="search" class="form-control" placeholder="Search keyword" id="modal-search-input">
                </div>
                <button type="submit" class="theme_button">Search</button>
            </form>
        </div>
    </div>

    <!-- wrappers for visual page editor and boxed version of template -->
    <div id="canvas">
        <div id="box_wrapper">

            <!-- template sections -->

            <section class="page_topline ds table_section transparent_section columns_padding_0">
                <div class="fluid-container">
                    <div class="row">
                        <div class="col-sm-3 col-xs-12 text-center text-sm-left">
                            <div class="page_social_icons">
                                @*<a class="social-icon color-icon soc-facebook" href="#" title="Facebook"></a>*@
                                @*<a class="social-icon color-icon soc-twitter" href="#" title="Twitter"></a>
                                    <a class="social-icon color-icon soc-youtube" href="#" title="Youtube"></a>*@
                            </div>
                        </div>

                        <div class="col-sm-6 col-xs-12 text-center">
                            <h4>
                                Red Juventud Sindical
                                #unidoscon<span style="font-weight:900">MARINA</span>
                                @*<a href="./" class="logo logo_image">
                                        <img src="~/Content/images/logo.png" alt="">
                                    </a>*@

                            </h4>
                        </div>

                        <div class="col-sm-3 col-xs-12 text-center text-sm-right">
                            <div class="top_meta">
                                @*<i class="fa fa-phone highlight"></i>
                                    <span class="vidaloka grey">1 (800) 253 76 84</span>*@

                            </div>
                        </div>

                    </div>
                </div>
            </section>

            <header class="page_header header_white columns_padding_0">
                <div class="fluid-container">
                    <div class="row display_table_md">
                        <div class="col-lg-2 col-md-3 col-xs-6 nowrap hidden-md display_table_cell_md hidden-xs">
                            <div class="page_social_icons">
                                @*<a class="social-icon color-icon soc-facebook" href="#" title="Facebook"></a>
                                <a class="social-icon color-icon soc-twitter" href="#" title="Twitter"></a>
                                <a class="social-icon color-icon soc-youtube" href="#" title="Youtube"></a>*@
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 text-right text-md-center display_table_cell_md">
                            <!-- main nav start -->
                            <nav class="mainmenu_wrapper inline-block">
                                <ul class="mainmenu nav sf-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Home")">Inicio</a>
                                    </li>

                                    <li>
                                        <a href="@Url.Action("marina_del_pilar", "Acerca")">Candidata</a>
                                    </li>



                                    <!-- blog -->
                                    <!-- eof blog -->
                                    <!-- gallery -->
                                    @*<li>
                                            <a href="">Eventos</a>

                                        </li>*@
                                    <!-- eof Gallery -->
                                    <!-- shop -->
                                    <li>
                                        <a href="@Url.Action("Index", "Capacitaciones")">Capacitaciones</a>

                                    </li>


                                    <!-- eof pages -->
                                    <!-- contacts -->
                                    @*<li>
                                            <a href="">Contacto</a>
                                        </li>*@
                                    <!-- eof contacts -->

                                </ul>
                            </nav>
                            <!-- eof main nav -->
                            <span class="toggle_menu">
                                <span></span>
                            </span>
                            <a href="@Url.Action("Index", "Registro")" class="theme_button color4 donate">Registro</a>
                        </div>
                        <div class="col-lg-2 col-md-3 text-right nowrap hidden-md hidden-sm hidden-xs display_table_cell_md">
                            <div class="top_meta">
                                @*<i class="fa fa-phone highlight"></i>
                                    <span class="vidaloka grey">1 (800) 253 76 84</span>
                                    <a href="#" class="search_modal_button">
                                        <i class="fa fa-search highlight"></i>
                                    </a>*@
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <div class="">
                @RenderBody()


            </div>

            <footer class="page_footer parallax ds section_padding_100 columns_padding_25">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            <div class="media">
                                <div class="media-left">
                                    @*<img class="media-object" src="~/Content/images/logo.png" alt="">*@
                                </div>
                                <div class="media-body">
                                    <h4 class="bottommargin_0 topmargin_5">
                                        #unidoscon
                                        <br> Marina
                                    </h4>
                                </div>
                            </div>
                            <p class="topmargin_20">
                                Se parte de la red Juventud Sindical, la voz del cambio esta en nuestra Juventud
                            </p>
                        </div>

                        <div class="col-md-4 col-sm-6">
                            <h4 class="bottommargin_30 topmargin_5">Te escuchamos</h4>
                            <form class="contact-form" method="post" action="/">

                                <p class="contact-form-name">
                                    <label for="footer-name" class="sr-only">
                                        Nombre completo
                                        <span class="required">*</span>
                                    </label>
                                    <input type="text" aria-required="true" size="30" value="" name="name" id="footer-name" class="form-control with-icon" placeholder="">
                                    <i class="fa fa-user"></i>
                                </p>
                                <p class="contact-form-email">
                                    <label for="footer-email" class="sr-only">
                                        Email
                                        <span class="required">*</span>
                                    </label>
                                    <input type="email" aria-required="true" size="30" value="" name="email" id="footer-email" class="form-control with-icon" placeholder="">
                                    <i class="fa fa-envelope"></i>
                                </p>
                                <p class="contact-form-message">
                                    <label for="footer-message" class="sr-only">Message</label>
                                    <textarea aria-required="true" rows="6" cols="45" name="message" id="footer-message" class="form-control with-icon" placeholder=""></textarea>
                                    <i class="fa fa-pencil"></i>
                                </p>
                                <p class="contact-form-submit topmargin_40">
                                    <button type="submit" id="footer_contact_form_submit" name="contact_submit" class="theme_button color1 margin_0">Enviar</button>
                                </p>

                            </form>
                        </div>

                        <div class="col-md-4 col-sm-6">
                            <h4 class="bottommargin_30 topmargin_5">Contáctanos</h4>



                            <div class="media small-teaser">
                                <div class="media-left right-15">
                                    <i class="fa fa-envelope-o highlight fontsize_14"></i>
                                </div>
                                <div class="media-body">
                                    <a href="mailto:Contacto@unidosconmarina.com">contacto@unidosconmarina.com</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </footer>

            <section class="page_copyright section_padding_45 ds columns_margin_0">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <p>
                                © Desarrollado por
                                <a href="#">Dreamcatcher</a>. Todos los derechos reservados
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <script src="~/Content/js/compressed.js"></script>
    <script src="~/Content/js/main.js"></script>

</body>
</html>