webadmin/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UPM.Entities;
using webadmin.Models;

namespace webadmin.Controllers
{
    public class BannersController : Controller
    {
        private UnidosconmarinaEntities db = new UnidosconmarinaEntities();

        // GET: Banners
        public ActionResult Index()
        {
            return View(db.Banners.ToList());
        }

        // GET: Banners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Banners/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,url_foto,estatus,link,usuarioRegistro,usuarioUpdate,fechaRegistro,fechaupdate")] Banner banner, HttpPostedFileBase file)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {

                    if (file != null)
                    {
                        string NombreArchivo = System.IO.Path.GetFileName(file.FileName);
                        string physicalPath = Server.MapPath("~/Content/images/banners/" + NombreArchivo);
                        file.SaveAs(physicalPath);
                        banner.url_foto = NombreArchivo;

                    }
                    db.Banners.Add(banner);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(banner);
            } 
            else
            {
                return View("~/Views/Account/Login.cshtml");
            }
        }

        // GET: Banners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banners.Include(a => a.AspNetUser).FirstOrDefault(x => x.Id == id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Banners/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,url_foto,estatus,link,usuarioRegistro,usuarioUpdate,fechaRegistro,fechaupdate")] Banner banner, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    string NombreArchivo = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/images/banners/" + NombreArchivo);
                    file.SaveAs(physicalPath);
                    banner.url_foto = NombreArchivo;
                }
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banner);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> EliminarAsync(Banner data)
        {
            try
            {
                Banner banner = db.Banners.Find(data.Id);
                db.Banners.Remove(banner);
                await db.SaveChangesAsync();

                return Json(new { accion = true, Msg = "Se ha eliminado correctamente" });
            }
            catch (DbEntityValidationException ex)
            {
                var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);

                var fullErrorMessage = string.Join("; ", errorMessages);

                var exceptionMessage = string.Concat(ex.Message, " The validation errors are: ", fullErrorMessage);

                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
            catch (Exception e)
            {
                return Json(new { accion = false, Msg = e.Message });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webadmin/Views/Banners/Create.cshtml
@using Microsoft.AspNet.Identity;
@model UPM.Entities.Banner

@{
    ViewBag.Title = "Create";
    var UserId = User.Identity.GetUserId();
    var userName = User.Identity.GetUserName();
}

<!-- @{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            Catálogos
        </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "Banners")" class="kt-subheader__breadcrumbs-link">
                Banners
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Agregar Banner
            </a>

            <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
        </div>
    </div>

</div>
<!-- end:: Subheader -->
@using (Ajax.BeginForm("Create", "Banners", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "successAction"

},
                new { @id = "modalForm", enctype = "multipart/form-data" }
                ))
{

    @Html.AntiForgeryToken()
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

        <div class="kt-portlet kt-portlet--mobile">

            <div class="kt-portlet__body">
                <h4>Agregar Banner</h4>
                <hr />
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <br />
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="fileinput-new img-thumbnail" style="width: 780px; height: 266px;">
                                <img src="~/assets/media/icons/camera2.png" alt="...">
                            </div>
                            <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 1280px; max-height: 366px;"></div>
                            <div>
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">Elegir Foto</span>
                                    <span class="fileinput-exists">Cambiar</span>
                                    <input type="file" name="file" id="file">
                                </span>
                                <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                            </div>
                        </div>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">
                        <div class="form-group">

                            <div class="">
                                <div class="checkbox">
                                    @Html.LabelFor(model => model.estatus, "Se publica?", htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.estatus)
                                    @Html.ValidationMessageFor(model => model.estatus, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div>

                                <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @userName</span>
                                @Html.HiddenFor(model => model.usuarioRegistro, new { Value = UserId, htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.usuarioRegistro, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Usuario de Registro
                            </span>
                        </div>

                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div>
                                @Html.EditorFor(model => model.fechaRegistro, new { htmlAttributes = new { Value = System.DateTime.Now.ToString("MM/dd/yyyy"), @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5" } })
                                @Html.ValidationMessageFor(model => model.fechaRegistro, "", new { @class = "text-danger" })
                            </div>
                            <span style="padding-left:10px; font-size:12px;">
                                Fecha Registro
                            </span>
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Registrar" />
                    </div>
                </div>

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/assets/js/programacion/list.js"></script>
}

webadmin/Views/Banners/Delete.cshtml
@model UPM.Entities.Banner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url_foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioUpdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaupdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaupdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

webadmin/Views/Banners/Details.cshtml
@model UPM.Entities.Banner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Banner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url_foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuarioUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioUpdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaupdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaupdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

webadmin/Views/Banners/Edit.cshtml
@using Microsoft.AspNet.Identity;
@model UPM.Entities.Banner


@{
    ViewBag.Title = "Edit";
    var UserId = User.Identity.GetUserId();
    var userName = User.Identity.GetUserName();
}

@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            CATALOGOS
        </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "Empresa")" class="kt-subheader__breadcrumbs-link">
                Banners
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Editar Banner
            </a>

        </div>
    </div>

</div>
<!-- end:: Subheader -->
@using (Ajax.BeginForm("Edit", "Empresa", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "successAction"

},
                            new { @id = "modalForm", enctype = "multipart/form-data" }
                            ))
{

    @Html.AntiForgeryToken()
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

        <div class="kt-portlet kt-portlet--mobile">

            <div class="kt-portlet__body">

                <div class="form-horizontal">
                    <h4>Editar Banner</h4>
                    <hr />
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new img-thumbnail" style="width: 580px; height: 266px;">
                                    @if (!string.IsNullOrEmpty(Model.url_foto))
                                    {
                                        <img src="~/Content/images/banners/@Model.url_foto " alt="..." style="max-width: 580px; max-height: 266px;">
                                        @Html.HiddenFor(model => model.url_foto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    }
                                    else
                                    {
                                        <img src="~/assets/media/icons/camera2.png" alt="...">
                                    }
                                </div>
                                <div class="fileinput-preview fileinput-exists img-thumbnail" style="max-width: 580px; max-height: 266px;"></div>
                                <div>
                                    <span class="btn btn-default btn-file">
                                        <span class="fileinput-new">Elegir Foto</span>
                                        <span class="fileinput-exists">Cambiar</span>
                                        <input type="file" name="file" id="file">
                                    </span>
                                    <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            @if (ViewBag.imageBytes != null)
                            {

                                <img width="150" height="150" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(ViewBag.imageBytes))" />
                            }
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-1">
                            <div class="form-group">
                                <br />
                                <div class="">
                                    <div class="checkbox">
                                        @Html.LabelFor(model => model.estatus, "Se publica?", htmlAttributes: new { @class = "control-label" })
                                        @Html.EditorFor(model => model.estatus)
                                        @Html.ValidationMessageFor(model => model.estatus, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>

                                    <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @Model.AspNetUser.Email</span>
                                    @Html.HiddenFor(model => model.usuarioRegistro, new {  htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.usuarioRegistro, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Usuario de Registro
                                </span>
                            </div>

                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div>
                                    @Html.TextBoxFor(model => model.fechaRegistro, "{0:yyyy-MM-dd}", htmlAttributes: new {  @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5"  })
                                    @Html.ValidationMessageFor(model => model.fechaRegistro, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Fecha Registro
                                </span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div>

                                    <span class="kt-header__topbar-username kt-hidden-mobile form-control" style="background-color:#f5f5f5"> @userName</span>
                                    @Html.HiddenFor(model => model.usuarioUpdate, new { Value = UserId, htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.usuarioUpdate, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Usuario de Actualización
                                </span>
                            </div>

                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div>
                                    @Html.EditorFor(model => model.fechaupdate, new { htmlAttributes = new { Value = System.DateTime.Now.ToString("MM/dd/yyyy"), @class = "form-control", @readonly = "readonly", @style = "background-color:#f5f5f5" } })
                                    @Html.ValidationMessageFor(model => model.fechaupdate, "", new { @class = "text-danger" })
                                </div>
                                <span style="padding-left:10px; font-size:12px;">
                                    Fecha Actualización
                                </span>
                            </div>

                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Editar" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

webadmin/Views/Banners/Index.cshtml
@model IEnumerable<UPM.Entities.Banner>
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}


<div>

    <input type="hidden" id="hView" value='@ViewContext.RouteData.Values["controller"].ToString()' />
</div>
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            Cátalogos
        </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "ClientesPedidos")" class="kt-subheader__breadcrumbs-link">
                Banners
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="@Url.Action("Index", "ClientesPedidos")" class="kt-subheader__breadcrumbs-link">
                Listado
            </a>

        </div>
    </div>

</div>
<!-- end:: Subheader -->
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">

    <div class="kt-portlet kt-portlet--mobile">

        <div class="kt-portlet__body">
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions" style="text-align:right">

                        <a href="@Url.Action("Create", "Banners")" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            Agregar Banners
                        </a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <!--begin: Datatable -->
                <table class="dataTable table table-striped- table-bordered table-hover table-checkable no-wrap display" data-order="[[2, &quot;asc&quot;]]">
                    <thead>
                        <tr>
                            <th></th>

                            <th data-orderable="false" data-searchable="false" data-visible="false">ID</th>
                            <th class="all">Banner</th>
                            <th class="all">Publicación</th>
                            <th class="all">Actualización</th>
                            <th class="all">Editar</th>
                            <th class="all">Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td></td>
                            <td data-info="ID">
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td data-info="Banners">
                                <div class="fileinput-new img-thumbnail">
                                    <img src="~/Content/images/banners/@Html.DisplayFor(modelItem => item.url_foto)" alt="..." style="width:100%; height:100%;">
                                </div>
                            </td>
                            <td data-info="activacion">
                                @Html.LabelFor(modelItem => item.estatus, "Se publica?", htmlAttributes: new { @class = "control-label" })
                                @Html.DisplayFor(modelItem => item.estatus)
                                @Html.ValidationMessageFor(modelItem => item.estatus, "", new { @class = "text-danger" })
                            </td>
                            <td data-info="Actualización">

                            @if (item.fechaupdate != null)
                            {
                                @Html.DisplayFor(modelItem => item.AspNetUser.Email)
                                <br />
                                @Convert.ToDateTime(item.fechaRegistro).ToString("dd/MM/yyyy")
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.AspNetUser1.Email)
                                <br />
                                @Convert.ToDateTime(item.fechaupdate).ToString("dd/MM/yyyy")
                            }


                            </td>
                            <td>
                                <a href="@Url.Action("Edit", "Banners", new { id = item.Id })">
                                    <span class="fa fa-edit fa-lg" aria-hidden="true"></span>
                                </a>
                            </td>
                            <td>
                                <span class="fa fa-trash fa-lg" aria-hidden="true" onclick="openModalEliminar(@item.Id)"></span>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>

                <!--end: Datatable -->
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAddEliminar" tabindex="-1" role="dialog" aria-labelledby="modalAddEliminar" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Elemento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                </button>
            </div>
            <div class="modal-body">
                <form id="frmFEliminar" enctype="multipart/form-data">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            <input type="hidden" name="id" id="id" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-12">
                            <h5>¿Estas seguro que deseas eliminar este Banners?</h5>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button id="btnFinalizarEvaluacion" type="button" class="btn btn-primary" onclick="eliminar('@Url.Action("EliminarAsync", "Banners")');">Finalizar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function eliminar(url) {
        Swal.fire({
            title: 'Procesando!',
            html: '',
            onBeforeOpen: () => {
                Swal.showLoading()
                return new Promise((resolve) => {
                    var formData = new FormData($('form#frmFEliminar')[0]);

                    $.ajax({
                        type: "POST",
                        url: url,
                        data: formData,
                        dataType: 'json',
                        contentType: false,// "multipart/form-data",
                        processData: false,
                        success: function (result) {
                            if (result.accion) {
                                Swal.fire({
                                    title: 'Realizado!',
                                    text: 'Se ha eliminado correctamente',
                                    type: 'success',
                                    onClose: () => {
                                        window.location.reload();
                                    }
                                });
                            }
                            else
                                Swal.fire('Ops!','No se puede eliminar el banners pedido.', 'error');
                        },
                        error: function (error) {
                            Swal.fire('Ops!', 'No se puede eliminar el banner.', 'error');
                        }
                    });

                })
            },
        }).then((result) => {
            if (result.value) {
                Swal.fire({
                    title: 'Realizado!',
                    text: 'Se ha eliminado correctamente',
                    type: 'success',
                    onClose: () => {
                        window.location.reload();
                    }
                });
            }
        });
    }
</script>
<script type="text/javascript">
    function openModalEliminar(id) {
        var modal = $('#modalAddEliminar');
        modal.find('form')[0].reset();
        modal.find('input#id').val(id);
        modal.modal('show');
    }
</script>